In [1]:
#Dependencies
import pandas as pd
import geopandas as gpd
import matplotlib.pyplot as plt

In [2]:
# Read the CSV file
analysis_data= pd.read_csv('analysis_data.csv')

# Display the first few rows of the DataFrame
analysis_data.head()

,Year,state,State_Pct_Telehealth,Rural_Pct_Telehealth,Urban_Pct_Telehealth,FID,fips,County Population,County Pop Per Sq Mile,Fixed Internet Subscribers,...,Number of PCPs per 100k,Number of Dentists per 100k,Number of Mental Health per 100k,Number of Adults in poor or Fair health,Rural Population,Share of Pop in Rural Area,Urban Population,Share of Pop in Urban Area,Number of Drug Related Deaths per 100k,Number of Opiod Related Deaths per 100k
0,2023,Alabama,0.0713,0.0661,0.0732,Connect2Health_2023_state.fid-1c4f9cde_18cec2a...,1,4903185,96.80,75,...,65.00,49.89,108.30,1048095,2024944,41.3,2878241,58.7,16.5,7.9
1,2023,Alaska,0.1580,0.1682,0.1465,Connect2Health_2023_state.fid-1c4f9cde_18cec2a...,2,731545,1.28,80,...,94.32,102.25,499.63,113872,262036,35.8,469509,64.2,17.1,11.5
2,2023,Arizona,0.1549,0.1526,0.1553,Connect2Health_2023_state.fid-1c4f9cde_18cec2a...,4,7278717,64.08,85,...,64.68,63.03,140.19,1355532,922084,12.7,6356633,87.3,22.5,13.9
3,2023,Arkansas,0.1070,0.0906,0.1203,Connect2Health_2023_state.fid-1c4f9cde_18cec2a...,5,3017804,57.99,67,...,66.27,47.55,236.36,702297,1342675,44.5,1675129,55.5,14.5,6.8
4,2023,California,0.2743,0.2530,0.2768,Connect2Health_2023_state.fid-1c4f9cde_18cec2a...,6,39512223,253.64,89,...,79.87,87.02,373.39,6959513,2415048,6.1,37097175,93.9,12.4,5.8

In [3]:
#create DF to merge with map to show density by "State_Pct_Telehealth"

analysis_stateTHpct=analysis_data[["state", "State_Pct_Telehealth"]]
analysis_stateTHpct.head()

        state  State_Pct_Telehealth
0     Alabama                0.0713
1      Alaska                0.1580
2     Arizona                0.1549
3    Arkansas                0.1070
4  California                0.2743

In [11]:
# Load the shapefile with state geometries
us_states = gpd.read_file(gpd.datasets.get_path('naturalearth_lowres'))

# Merge the shapefile data with your dataset
#StateTHpctMap = us_states.merge(analysis_stateTHpct, how='left', left_on='name', right_on='state')

# Plotting the choropleth map
#fig, ax = plt.subplots(1, 1, figsize=(10, 6))
#StateTHpctMap.plot(column='State_Pct_Telehealth', cmap='YlGnBu', linewidth=0.8, ax=ax, edgecolor='0.8', legend=True)
#plt.title('Choropleth Map by State')
#plt.axis('off')  # Hide axis
#plt.show()

,pop_est,continent,name,iso_a3,gdp_md_est,geometry
0,920938,Oceania,Fiji,FJI,8374.0,"MULTIPOLYGON (((180.00000 -16.06713, 180.00000..."
1,53950935,Africa,Tanzania,TZA,150600.0,"POLYGON ((33.90371 -0.95000, 34.07262 -1.05982..."
2,603253,Africa,W. Sahara,ESH,906.5,"POLYGON ((-8.66559 27.65643, -8.66512 27.58948..."
3,35623680,North America,Canada,CAN,1674000.0,"MULTIPOLYGON (((-122.84000 49.00000, -122.9742..."
4,326625791,North America,United States of America,USA,18560000.0,"MULTIPOLYGON (((-122.84000 49.00000, -120.0000..."